#!/bin/bash

# Sample Script for making a html file

title="Command Line is life"
CURRENT_DATE=$(date +"%T")

cat <<- _EOF_
	
    <html>
    <head>
        <title>
        $title $HOSTNAME
        </title>
    </head>

    <body>
        <h1>$title $HOSTNAME
        <p>Update on $CURRENT_DATE by $USER</p>
    </body>
    </html>

_EOF_